---

- name: Install epel-release
  yum: name='epel-release' state=present

- name: Install Graphite dependencies
  yum: name={{ item }} state=present
  with_items:
    - python
    - python-pip
    - python-devel
    - python-cairocffi
    - python-gunicorn
    - python-django
    - python-django-tagging
    - python-twisted-core
    - fontconfig
    - cairo-devel
    - pytz
    - gcc
    - wget
    - supervisor
    - nginx
    - git
    - memcached
    - nodejs


- name: Get installed pip version
  command: pip --version
  register: pip_version_output
  ignore_errors: yes
  changed_when: false

- name: Download get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py
           dest=/tmp/get-pip.py

# Install pip if it's not already installed, or if
# the desired versions of pip aren't installed
# The regular expression extracts '9.0' out of '9.0.*'
- name: Install Or Update pip
  command: "python get-pip.py pip=={{ pip_version }}"
  when:  pip_version_output | failed or not pip_version_output.stdout | search(pip_version)
  args:
    chdir: /tmp
